### ISSUE TITLE
400 Bad Request - using namedQuery with GET and 

### ISSUE THREAD

**Issue by garybond** [ChilliCream/hotchocolate#2236]
I have been attempting to use ```HotChocolate.PersistedQueries.FileSystem``` for GET requests, but I always get a 400 response when I make a GET request with the parameter ```?namedQuery=foo```

If I make a POST request with the following request body, I get the expected results.
``` json
{
    "namedQuery": "foo"
}
```

**To Reproduce**
1. Using latest stable HotChocolate 10.5.2 (main branch)
2.  Open the Examples -> AspNetCore.StarWars project
3. Add a project to the solution and project reference to AspNetCore.StarWars:
```csharp
<ProjectReference Include="..\..\src\Core\PersistedQueries.FileSystem\PersistedQueries.FileSystem.csproj" />
```
4. In the ```Startup.cs```, change the GraphQL setup to use peristed queries:
```csharp
            // Add GraphQL Services
            services.AddGraphQL(sp => SchemaBuilder.New()
                .AddServices(sp)

                // Adds the authorize directive and
                // enable the authorization middleware.
                .AddAuthorizeDirectiveType()

                .AddQueryType<QueryType>()
                .AddMutationType<MutationType>()
                .AddSubscriptionType<SubscriptionType>()
                .AddType<HumanType>()
                .AddType<DroidType>()
                .AddType<EpisodeType>()
                .Create(),
                b =>
                {
                    b.UsePersistedQueryPipeline();
                });

            services.AddReadOnlyFileSystemQueryStorage("./queries");
```
5. Add a folder+file '\queries\foo' at the root of the AspNetCore.StarWars project.
6. Put the following query in the foo file:

```graphql
{
  hero {
    name
    appearsIn
  }
}
```
7. Run the AspNetCore.StarWars project.
8. Issue a POST request for the named query:
```
curl -X POST \
  https://localhost:44356/graphql \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d '{
    "namedQuery": "foo"
}'
```
You get the expected result of:
```json
{
    "data": {
        "hero": {
            "name": "R2-D2",
            "appearsIn": [
                "NEWHOPE",
                "EMPIRE",
                "JEDI"
            ]
        }
    }
}
```
9. Now make a GET request:
```
curl -X GET \
  'https://localhost:44356/graphql?namedQuery=foo' \
  -H 'cache-control: no-cache'
```
**You now get a 400 Bad Request response.**

**Expected behavior**
The response from both a POST request and a GET request for the same named query SHOULD return the same response, no?

**Additional context**
I was also seeing this in previous 10.4.x versions, but unsure how far back it goes.

**Comment by michaelstaib** [comment]
This might be a documentation error. If you use `id` it should work just fine.

```
curl -X POST \
  https://localhost:44356/graphql \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d '{
    "id": "foo"
}'
```

**Comment by garybond** [comment]
Hi @michaelstaib,
No sorry, that doesn't work. That responds with a 404.
With `namedQuery`, it at least gets handled by the `HttpGetMiddleware`, but there's no provision for matching a parameter `id` that I can see:

```csharp
        private const string _namedQueryIdentifier = "namedQuery";
        private const string _queryIdentifier = "query";

        protected override bool CanHandleRequest(HttpContext context)
        {
            return string.Equals(
                context.Request.Method,
                HttpMethods.Get,
                StringComparison.Ordinal) &&
                    HasQueryParameter(context);
        }

        private static bool HasQueryParameter(HttpContext context)
        {
#if ASPNETCLASSIC
            return context.Request.Query[_queryIdentifier] != null
                || context.Request.Query[_namedQueryIdentifier] != null;
#else
            return context.Request.Query[_queryIdentifier].Count != 0
                || context.Request.Query[_namedQueryIdentifier].Count != 0;
#endif
        }
```
 
I think the problem is further down the pipeline...

**Comment by garybond** [comment]
@michaelstaib although, the `id` parameter DOES work with a POST

**Comment by michaelstaib** [comment]
So, the issue is with HTTP GET requests. I will issue a fix for this week.

**Comment by garybond** [comment]
@michaelstaib thanks.
I debugged a bit further through and it is this code in `QueryRequestBuilder.cs` that is throwing an exception because the `querySource` parameter is null:
```csharp
        public IQueryRequestBuilder SetQuery(string querySource)
        {
            if (string.IsNullOrEmpty(querySource))
            {
                throw new ArgumentException(
                    AbstractionResources.QueryRequestBuilder_QueryIsNullOrEmpty,
                    nameof(querySource));
            }

            _query = new QuerySourceText(querySource);
            return this;
        }
```

**Comment by michaelstaib** [comment]
This one is fixed.

**Comment by michaelstaib** [comment]
- [ ] we should create an explicit test that refers to this issue.

**Comment by garybond** [comment]
Added notes to the [Slack channel](https://hotchocolategraphql.slack.com/archives/C01EUDJ7ETU/p1606302200117700?thread_ts=1605870650.085100&cid=C01EUDJ7ETU) for v10 -> v11 migration on why I think this still isn't working.

**Comment by michaelstaib** [comment]
This is fixed now .... look at:
https://github.com/ChilliCream/hotchocolate/blob/aa8d21485e87aae0b3d59e61e418e83bffa9cb6f/src/HotChocolate/AspNetCore/src/AspNetCore/Serialization/DefaultHttpRequestParser.cs#L50

**Comment by garybond** [comment]
Thank you @michaelstaib, that has indeed fixed the issue that was blocking us from using v11

**Comment by michaelstaib** [comment]
awesome :)
