### ISSUE TITLE
Unhandled OperationCanceled Exception

### ISSUE THREAD

**Issue by dschmittlan** [ChilliCream/hotchocolate#2408]
When using GraphQL Subscriptions an unhandled OperationCanceled Exception is thrown when a client closes the connection (e.g. by closing the browser tab). I wonder if this is the expected behaviour and if so how to handle this correctly?

```
Microsoft.AspNetCore.Server.Kestrel: Error: Connection id "0HM3914R7M96M", Request id "0HM3914R7M96M:00000001": An unhandled exception was thrown by the application.

System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.IO.Pipelines.Pipe.PrepareFlush(CompletionData& completionData, ValueTask`1& result, CancellationToken cancellationToken)
   at System.IO.Pipelines.Pipe.FlushAsync(CancellationToken cancellationToken)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.FlushAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.MessageReceiver.WriteMessageDelimiterAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.MessageReceiver.ReceiveAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.WebSocketSession.HandleAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.WebSocketSession.HandleAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.SubscriptionMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpGetSchemaMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
```
I'm using HotChocolate version 10.4.3

**Comment by michaelstaib** [comment]
The issue here is that the connection is closed by the client which will, in turn, causes the cancellation. 

We probably should catch this one in the `SubscriptionMiddleware`. I will put this in the 11 backlog and we will review how this works now with the new lifetime handling.

Thanks for reporting.

**Comment by michaelstaib** [comment]
This one is fixed.

**Comment by sanchez** [comment]
I am currently unable to upgrade to 11, is there a way I can capture and handle this easily within 10? Thanks

**Comment by f1nan** [comment]
We wrote a custom middleware to catch the `OperationCacnceledException` as a workaround. If you don't know how to write a middleware this [article](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-5.0) should be helpful.

**Comment by sanchez** [comment]
Thanks for that, I have written up a bit of middleware but I am still getting the same exception popup. At the moment we seemingly have an issue where one user will cancel their subscription and it will just cascade to a bunch of people being cancelled and ultimate the whole server crashes. Sadly we have only been able to reproduce in production and the system is within a docker environment so no dumps available 😢 I understand if this is not related to this issue or should be taken elsewhere, thanks!

Exception being thrown:
![image](https://user-images.githubusercontent.com/5264697/130380623-3488f0e3-127e-48fa-8994-8b49efa2b1df.png)

Exception catching code:
![image](https://user-images.githubusercontent.com/5264697/130380698-40de748f-3f99-47f9-8c98-90d55015a1b0.png)

As you can see, the exception is being captured, my hope was that by adding the exception it would stop the bubbling up of the exception and crashing the server, but there just seems to be a large amount of exceptions being thrown all at once, ~50 exceptions within a single minute then our memory usage spikes to the limits of the hosting and everything restarts immediately
