### ISSUE TITLE
PooledDbContext injection not working in Code-First approach

### ISSUE THREAD

**Issue by DimitarKrastev** [ChilliCream/hotchocolate#3254]
**Describe the bug**
Retrieving EF DB context in Code-First approach resolver returns error "No service for type 'SomeDbContext' has been registered.
The usage is documented here: https://chillicream.com/docs/hotchocolate/integrations/entity-framework/#using-the-dbcontext

**To Reproduce**
Startup.cs
`
services.AddPooledDbContextFactory<MedicalDbContext>(options => 
    options.UseSqlServer(Configuration.GetConnectionString("SomeDatabase")), 128);`
QueryType.cs
```
public class QueryType: ObjectType
{
  
    protected override void Configure(IObjectTypeDescriptor descriptor)
    {
        descriptor.Field("someField")
            .UseDbContext<SomeDbContext>()
            .Type<SomeFieldType>()
            .Resolver((ctx, ct) => {
                return ctx.Service<SomeDbContext>().SomeFieldData;
            })
            .UseFiltering();
    }
}
```

Execute GraphQl Query
`{
	someField{
  	id,
  }
}`

Resulting error
`System.InvalidOperationException: 'No service for type 'SomeDbContext' has been registered.'`

Same exact setup, but with Pure Code First approach works just fine and the service is resolved:
```
[UseDbContext(typeof(SomeDbContext))]
[GraphQLType(typeof(SomeFieldType))]
public IQueryable<SomeField> GetSomeField(
    [ScopedService] SomeDbContext context) =>
    context.SomeFieldData
```

**Expected behavior**
DbContext service is resolved by creating (or obtaining an existing) instance using the pooled db context factory.

**Version:**
HotChocolate 11

**Insights:**
The creation of the DBContext instance seems to be working correctly by observing its constructor invokation.
It is only the access to it that is broken.
**Workarround:**
Credits: Paolo Go from Slack channel
Manually obtaining the service from the LocalContextData seems to be a feasible workarround.

```
descriptor.Field("someField")
    .Type<SomeFieldType>()
    .UseDbContext<SomeDbContext>()
    .Resolver((ctx, ct) => {
            return ((SomeDbContext)ctx.LocalContextData[typeof(SomeDbContext).FullName]).SomeEntries.FirstOrDefault();
    });```

**Comment by AAIING** [comment]
**I having some problem.**
"message": "The specified key `HCWebApplication3.DataContext` does not exist on `context.ScopedContextData`."

try to use ObjectTypeExtension: 
`public class ClienteTypeExtension : ObjectTypeExtension
    {

        protected override void Configure(IObjectTypeDescriptor descriptor)
        {
            
            descriptor.Name("Query");
            //
            descriptor.Field("GetClientes")
                .ResolveWith<ClienteResolver>(q => q.GetClientes(default!))
                //.Type<ListType<ClienteType>>()
                .Type<ClienteType>()
                .Name("GetAllClientes");
            
        }
    }`

Query class..

`    public class ClienteResolver
    {

    
        [UseDbContext(typeof(DataContext))]
        public IQueryable<Cliente> GetClientes([ScopedService] DataContext dataContext)
        {

            return dataContext.CLIENTE;
        }
`
Type GraphQL code-first..

` public class ClienteType : ObjectType<Cliente
    {
        //private readonly DataContext dataContext;
        protected override void Configure(IObjectTypeDescriptor<Cliente descriptor)
        {

            descriptor.Field(b => b.RUT)
                .Type<IntType>()
                .Name("rut");

            descriptor.Field(b => b.CONTRASENA)
                .Type<StringType>()
                .Name("contrasena");

            descriptor.Field(b => b.NOMBRE)
                .Type<StringType>()
                .Name("nombre");
        }
    }`

Startup.cs

`
 services.AddPooledDbContextFactory<DataContext>(options =>
services.AddGraphQLServer()
                    //SCHEMAS   
 
                    .AddQueryType(d => d.Name("Query"))
                    .AddType<ClienteTypeExtension>()`

**Comment by AAIING** [comment]
Adding .UseDbContext<DataContext>

` protected override void Configure(IObjectTypeDescriptor descriptor)
        {
            
            descriptor.Name("Query");
            //
            descriptor.Field("GetClientes")
                .ResolveWith<ClienteResolver>(q => q.GetClientes(default!))
                //.Type<ListType<ClienteType>>()
                .Type<ClienteType>()
                .UseDbContext<DataContext>()
                .Name("GetAllClientes");
            
        }`

Lauch new error: 

  **"message": "The parent cannot be casted to HCWebApplication3.Models.Cliente.",**

**Comment by AAIING** [comment]
Use .ResolveWith<>()

**Comment by PascalSenn** [comment]
@DimitarKrastev  what is ` .UseMyDbContext<SomeDbContext>()`?

**Comment by PascalSenn** [comment]
Also I guess this is resolved as it never really is a Service after all :) 
It is stored on the LocalContextData

**Comment by DimitarKrastev** [comment]
@PascalSenn A typo, I meant .UseDbContext<SomeDbContext>()

It is documented as the way to use DbContext here - https://chillicream.com/docs/hotchocolate/integrations/entity-framework#using-the-dbcontext

As stated in the ticket on the second line :)

**Comment by KreativJos** [comment]
> Also I guess this is resolved as it never really is a Service after all :)
> It is stored on the LocalContextData

Why, that seems to work indeed:

```
descriptor.Field("entities")
    .Type<ListType<NonNullType<EntityType>>>()
    .UseDbContext<DatabaseContext>()
    .Resolve<IQueryable<Entity>>(context =>
    {
        var db = context.GetDatabaseContext() ?? throw new ArgumentNullException(nameof(DatabaseContext));
    
        return db.Entities;
    });
```

This seems to be an issue with the documentation then?

**Comment by noufionline** [comment]
The documentation is still not updated I guess. The below code doesnt work.

 ```csharp
public class QueryType : ObjectType
{
    protected override void Configure(IObjectTypeDescriptor descriptor)
    {
        descriptor
            .Field("users")
            .UseDbContext<SomeDbContext>()
            .Resolver((ctx) =>
            {
                return ctx.Service<SomeDbContext>().Users;
            })
    }
}
```

**Comment by tobias-tengler** [comment]
@noufionline Documentation has been updated and I've added a `DbContext<T>` extension method to the `IResolverContext` in 12.0.0-rc.12. 

You can now do:
```csharp
public class QueryType : ObjectType
{
   protected override void Configure(IObjectTypeDescriptor descriptor)
   {
       descriptor
           .Field("users")
           .UseDbContext<SomeDbContext>()
           .Resolver((ctx) =>
           {
               return ctx.DbContext<SomeDbContext>().Users;
           })
   }
}
```
