### ISSUE TITLE
[PREVIEW]Redis stitching no longer works in v12 previews

### ISSUE THREAD

**Issue by davesimtech** [ChilliCream/hotchocolate#4049]
**Describe the bug**
I currently have a gateway api that uses Redis stitching to stitch multiple apis. This however no longer seems to be working after upgrading to v12 from v11. Currently getting the following error message:

`HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to resolve dependencies None: Uuid! for type `Query`. (HotChocolate.Types.ObjectType)
2. Unable to resolve dependencies None: delegate for type `Mutation`. (HotChocolate.Types.ObjectType)
3. Unable to resolve dependencies None: Uuid! for type `Query`. (HotChocolate.Types.ObjectTypeExtension)
4. Unable to resolve dependencies None: delegate for type `Mutation`. (HotChocolate.Types.ObjectTypeExtension)`

**To Reproduce**
Reproduction with minimal code available here: https://github.com/davesimtech/hotchocolate-stitching

**Expected behavior**
Redis Stitching works after upgrading to v12

**Comment by matt-psaltis** [comment]
This one's stopping us from doing any meaningful v12 testing on our project to help out with RC0 testing. Is the 2021-08 milestone part of v12.0 or the one after? When I open the milestone, it says 'HC-2021-06 AKA Version 12' so I'm confused in the timing :D

**Comment by michaelstaib** [comment]
So I was hoping it is resolved.... tests are green. Strange... will have a look.

**Comment by matt-psaltis** [comment]
Oh if that's the case let me get specifics before you spend any time on it!

**Comment by michaelstaib** [comment]
Any update on this?

**Comment by matt-psaltis** [comment]
Turns out, the team (me) wasn't clearing the redis cache between running v11 & v12 code branches. What's the version compatibility story between redis backed remote graphql schemas from v11 vs v12? A one time redis cache clear is fine for us but it'd be great if some sort of versioning / compatibility check flagged this. The error message is a long way from anything Redis related so its harder to diagnose. What do you think?

**Comment by davesimtech** [comment]
I'm still getting this issue even when turning off Redis at the moment in rc.6

**Comment by PascalSenn** [comment]
@davesimtech  can you share a minimal repro with us? :)

**Comment by davesimtech** [comment]
Yeah there's a link to my repo in the original issue :)

**Comment by mickdelaney** [comment]
I'm having the same problem, using v 12.0.0-rc.7 

1. Unable to resolve type reference `None: Uuid`. (HotChocolate.Types.InputObjectType)

**Comment by matt-psaltis** [comment]
Where are the schemas originating from? In the original sample repo above the source schema is using Uuid which in v12 has been changed to UUID Case sensitive. My issue was my redis cluster was still caching some service metadata from v11 which used the Uuid form. Manually clearing those redis entries or forcing a refresh to the v12 format resolved it immediately.

**Comment by mickdelaney** [comment]
@matt-psaltis yeah, looks like an older process was poking in the older version into the cache, even after i had cleared it. 

but now i have another issue that wasnt there in 11x. 

Unable to resolve type reference `None: ApplicationIdType!`. (HotChocolate.Types.InputObjectType)

Seems i need to share Types between the Gateway and downstream services ?

**Comment by michaelstaib** [comment]
I am closing this issue for now. We are now starting planing phase for V13 which will focus on schema stitching. Version 12 still has the V11 stitching layer.
