### ISSUE TITLE
Client can't stop when server completed.

### ISSUE THREAD

**Issue by CoreDX9** [ChilliCream/hotchocolate#4813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I don't think I made myself clear in #4810 . So I build a project to this issues.
StrawberryShake can't detect subscription has been completed by server. Subscription will can't cancel  in Banana Cake Pop 12.6.0. But version 12.6.1 can auto stop (maybe apollo client work well).
Please look at picture. When I click "Complete Subscription" button. Subscription on Banana Cake Pop stoped automatically. Server printed log to console(server work well). But console client(StrawberryShake) nothing happened. I want the console to print a log and exit.
``` csharp
subscription.Subscribe(
    x => Console.WriteLine(x?.Data?.OnMessage.Message),
    // error callback
    // It should be shown after click "Complete Subscription" button. or complete callback
    // But this will never happen.
    ex => Console.WriteLine($"Exception happened: {ex.Message}"),
    // complete callback
    // It should be shown after click "Complete Subscription" button. or error callback
    // But this will never happen.
    () => Console.WriteLine("The subscription stream was completed by server!"));
```

If StrawberryShake can stop subscription automatically like Banana Cak Pop 12.6.1. I can notify user that connetion has closed in Blazor app.
![2022-03-04-10-06-52](https://user-images.githubusercontent.com/26616055/156689204-cd702342-f269-41df-a778-e61250e5d296.gif)

### Steps to reproduce

1. run server and client
2. send some message
3. click "Complete Subscription" button
4. console client can't exit

### Additional Context?

This is [Test Project](https://github.com/CoreDX9/GraphqlSubscriptionTest) . Just run.

### Product

Strawberry Shake

### Version

12.6.1

**Comment by CoreDX9** [comment]
If I shutdown server. Banana Cake Pop and console client nothing happened. I think client should throw an network error Exception to notify program.
![新视频](https://user-images.githubusercontent.com/26616055/156695910-d3ce80be-97b0-4038-b143-69d5c6044ce1.gif)

**Comment by PascalSenn** [comment]
@michaelstaib  is this fixed in #4775 ?

**Comment by michaelstaib** [comment]
The server side is now fixed... I think rafi has the client-side also fixed with the next release.

@rstaib is the client disconnect now correctly detected? Can we close this?

**Comment by rstaib** [comment]
@michaelstaib release is on it's way right now ;-)

**Comment by rstaib** [comment]
I will close this issue as soon as the build is through 👍🏻

**Comment by CoreDX9** [comment]
@PascalSenn I Tested in 13.0-pre18, StrawberryShake still can't trigger OnComplete or OnError callback. If convert Subscribe to IAsyncEnumerable, it means async enumerator will never end. But the Subscribe can't receive message anymore (socket has closed).
If Subscribe can't complete whatever the reason unless disposed by myself. How can I notify user the subscription has dead or try reconnect automatically? I don't kown why the subscribe doesn't have new message, It's dead? Or there is really no new message?

**Comment by CoreDX9** [comment]
I think OnCompleted callback of console client will be triggered if add `observer.OnCompleted();` before `session.RequestSession.Dispose();`. https://github.com/ChilliCream/hotchocolate/blob/b56f0e96487fa7b2d4423d1cf1310b33aea73250/src/StrawberryShake/Client/src/Core/OperationExecutor.Observable.cs#L132-L134

In Microsoft Docs: [IObservable{T} Interface](https://docs.microsoft.com/en-us/dotnet/api/system.iobservable-1?view=net-6.0#examples)

``` csharp
   public void EndTransmission()
   {
      foreach (var observer in observers.ToArray())
         if (observers.Contains(observer))
            observer.OnCompleted();

      observers.Clear();
   }
```
IObservable should call observer's OnCompleted method to notify observer there is no further data is available.
